/* =====================================================================
   Breed cleaning lookup — inline version, works on a READ-ONLY connection.
   Creates nothing. Paste this whole block at the top of any query, then:

       LEFT JOIN breed_clean bc ON bc.raw_breed = <the breed name column>

   kind is one of:
       DOG          usable, a single pedigree breed
       MIXED        a mix or designer cross — keep in sales, drop from sizing
       CAT          cat
       OTHER ANIMAL rabbit, parrot and similar
       UNMAPPED     a real name we have not placed yet
       JUNK         placeholder or nonsense
   ===================================================================== */
WITH breed_clean (raw_breed, canonical, kind) AS (
  VALUES
    ('Shih Tzu', 'Shih Tzu', 'DOG'),
    ('Golden Retriever', 'Golden Retriever', 'DOG'),
    ('Labrador', 'Labrador Retriever', 'DOG'),
    ('Persian Cat', '(not a dog)', 'CAT'),
    ('Indie Dog', 'Indian Pariah (Indie)', 'DOG'),
    ('Beagle', 'Beagle', 'DOG'),
    ('Indie Cat', '(not a dog)', 'CAT'),
    ('German Shepherd', 'German Shepherd', 'DOG'),
    ('Husky', 'Siberian Husky', 'DOG'),
    ('Cocker Spaniel', 'Cocker Spaniel', 'DOG'),
    ('Pomeranian', 'Pomeranian', 'DOG'),
    ('Toy Poodle', 'Toy Poodle', 'DOG'),
    ('LLhasa APSO', 'Lhasa Apso', 'DOG'),
    ('Lhasa Apso', 'Lhasa Apso', 'DOG'),
    ('Maltese', 'Maltese', 'DOG'),
    ('Cat', '(not a dog)', 'CAT'),
    ('Rottweiler', 'Rottweiler', 'DOG'),
    ('maine coon', '(not a dog)', 'CAT'),
    ('pug', 'Pug', 'DOG'),
    ('French Bulldog', 'French Bulldog', 'DOG'),
    ('Doberman', 'Doberman', 'DOG'),
    ('Chow Chow', 'Chow Chow', 'DOG'),
    ('Mixed Breed', '(mixed breed)', 'MIXED'),
    ('Boxer', 'Boxer', 'DOG'),
    ('Pitbull', 'Amstaff / Pit-type', 'DOG'),
    ('Chihuahua', 'Chihuahua', 'DOG'),
    ('Toy Pomeranian', 'Pomeranian', 'DOG'),
    ('Dachshund', 'Dachshund', 'DOG'),
    ('Yorkshire Terrier', 'Yorkshire Terrier', 'DOG'),
    ('German Spitz', 'German Spitz', 'DOG'),
    ('shihtzu', 'Shih Tzu', 'DOG'),
    ('American Bully', 'Amstaff / Pit-type', 'DOG'),
    ('Indie', '(unusable)', 'JUNK'),
    ('Labrador Retriever', 'Labrador Retriever', 'DOG'),
    ('Siberian Husky', 'Siberian Husky', 'DOG'),
    ('indian spitz', 'Indian Spitz', 'DOG'),
    ('Tabby Cat', '(not a dog)', 'CAT'),
    ('DASHUND', 'Dachshund', 'DOG'),
    ('spitz', 'Indian Spitz', 'DOG'),
    ('Great Dane', 'Great Dane', 'DOG'),
    ('Lasa Apso', 'Lhasa Apso', 'DOG'),
    ('poodle', 'Standard Poodle', 'DOG'),
    ('Jack Russell Terrier', 'Jack Russell Terrier', 'DOG'),
    ('Saint Barnard', 'Saint Bernard', 'DOG'),
    ('lasa', 'Lhasa Apso', 'DOG'),
    ('Poodle Mixed', '(mixed breed)', 'MIXED'),
    ('domestic short hair', '(not a dog)', 'CAT'),
    ('Golden retreiver', 'Golden Retriever', 'DOG'),
    ('Poodle (Toy)', 'Toy Poodle', 'DOG'),
    ('labrador -Indie Mix', '(mixed breed)', 'MIXED'),
    ('Bichon Frize', 'Bichon Frise', 'DOG'),
    (' Maltipoo', '(mixed breed)', 'MIXED'),
    ('Dalmatian', 'Dalmatian', 'DOG'),
    ('Golden Doodle', '(mixed breed)', 'MIXED'),
    ('Pug', 'Pug', 'DOG'),
    ('Cane Corso', 'Cane Corso', 'DOG'),
    ('Himalayan Cat', '(not a dog)', 'CAT'),
    ('ginger cat', '(not a dog)', 'CAT'),
    ('Bull Mastiff', 'Bullmastiff', 'DOG'),
    ('Maltipoo', '(mixed breed)', 'MIXED'),
    ('Indie mix ', '(mixed breed)', 'MIXED'),
    ('mixed cat', '(not a dog)', 'CAT'),
    ('Calico', '(not a dog)', 'CAT'),
    ('Syberian Husky', 'Siberian Husky', 'DOG'),
    ('Bombay', '(not a dog)', 'CAT'),
    ('Ragdoll Cat', '(not a dog)', 'CAT'),
    ('English Bulldog', 'English Bulldog', 'DOG'),
    ('British Short Hair', '(not a dog)', 'CAT'),
    ('French Mastiff', 'Bullmastiff', 'DOG'),
    ('Corgi', 'Pembroke Corgi', 'DOG'),
    ('Poodle', 'Standard Poodle', 'DOG'),
    ('Labrador Retriever ', 'Labrador Retriever', 'DOG'),
    ('Akita', 'Akita', 'DOG'),
    ('Lab mix', '(mixed breed)', 'MIXED'),
    ('Black Labrador', 'Labrador Retriever', 'DOG'),
    ('mini poodle', 'Toy Poodle', 'DOG'),
    ('Bengal cat', '(not a dog)', 'CAT'),
    ('Havanese ', 'Havanese', 'DOG'),
    ('Bully', 'Amstaff / Pit-type', 'DOG'),
    ('Indie (With Fur)', 'Indian Pariah (Indie)', 'DOG'),
    ('Indian Spitz', 'Indian Spitz', 'DOG'),
    ('Cavalier King Charles Spaniel', 'Cavalier King Charles Spaniel', 'DOG'),
    ('Labrator', 'Labrador Retriever', 'DOG'),
    ('Samoyed', 'Samoyed', 'DOG'),
    ('mongrul', 'Indian Pariah (Indie)', 'DOG'),
    ('mix shitzu', '(mixed breed)', 'MIXED'),
    ('Rajapalayam', 'Rajapalayam', 'DOG'),
    ('Beagle', 'Beagle', 'DOG'),
    ('BelgiaMalinoisn', 'Belgian Malinois', 'DOG'),
    ('Lab', 'Labrador Retriever', 'DOG'),
    ('Shih Tzu Maltese mix', '(mixed breed)', 'MIXED'),
    ('shit tzu', 'Shih Tzu', 'DOG'),
    ('indie dog', 'Indian Pariah (Indie)', 'DOG'),
    ('miniature poodle', 'Toy Poodle', 'DOG'),
    ('Maltese pooh', '(mixed breed)', 'MIXED'),
    ('Culture Po', 'Pomeranian', 'DOG'),
    ('English Retriever', 'Golden Retriever', 'DOG'),
    (' Indie cat', '(not a dog)', 'CAT'),
    ('Mix Shih Tzu', '(mixed breed)', 'MIXED'),
    ('Rabbit', '(not a dog)', 'OTHER ANIMAL'),
    ('Pomerian', 'Pomeranian', 'DOG'),
    ('Border Collie', 'Border Collie', 'DOG'),
    ('Toy Poodle', 'Toy Poodle', 'DOG'),
    ('Himalayan Mastiff', 'Tibetan Mastiff', 'DOG'),
    ('Saint Bernard', 'Saint Bernard', 'DOG'),
    ('Turkish Van Cat', '(not a dog)', 'CAT'),
    ('Pekingnese', '(unmapped)', 'UNMAPPED'),
    ('little lion', '(not a dog)', 'OTHER ANIMAL'),
    ('Cockapoo', '(mixed breed)', 'MIXED'),
    ('Cavapooh', '(mixed breed)', 'MIXED'),
    ('Domestic Short Hair', '(not a dog)', 'CAT'),
    ('Basset Hound', 'Basset Hound', 'DOG'),
    ('Maine Coon Cat', '(not a dog)', 'CAT'),
    ('Mixed Cat', '(not a dog)', 'CAT'),
    ('Poddle mixed', '(mixed breed)', 'MIXED'),
    ('Serbian Cat', '(not a dog)', 'CAT'),
    ('Alaskan Malamute', 'Alaskan Malamute', 'DOG'),
    ('mini pom', 'Pomeranian', 'DOG'),
    ('Poodle (Miniature)', 'Toy Poodle', 'DOG'),
    ('Indies', '(unusable)', 'JUNK'),
    ('Germen sheperd', 'German Shepherd', 'DOG'),
    ('Molt', '(unusable)', 'JUNK'),
    ('Labrador-Indie Mix', '(mixed breed)', 'MIXED'),
    ('german shepherd/lab', '(mixed breed)', 'MIXED'),
    ('Persian & Indie Mix', '(not a dog)', 'CAT'),
    ('St Bernard', 'Saint Bernard', 'DOG'),
    ('Tibetan Mastiff', 'Tibetan Mastiff', 'DOG'),
    ('persian', '(not a dog)', 'CAT'),
    ('Miniature Schnauzer', 'Miniature Schnauzer', 'DOG'),
    ('Siamese Cat', '(not a dog)', 'CAT'),
    ('dogo argentino', 'Dogo Argentino', 'DOG'),
    ('Bull Dog', 'English Bulldog', 'DOG'),
    ('cocopoo', '(mixed breed)', 'MIXED'),
    ('Ginger Cat', '(not a dog)', 'CAT'),
    ('Golden Indie mix', '(mixed breed)', 'MIXED'),
    ('Chippiparai', 'Chippiparai', 'DOG'),
    ('american Pitbull', 'Amstaff / Pit-type', 'DOG'),
    ('Siberian cat', '(not a dog)', 'CAT'),
    ('Japanese Spitz', 'Japanese Spitz', 'DOG'),
    ('Lhasa Apso Mix', '(mixed breed)', 'MIXED'),
    ('Siberian', '(not a dog)', 'CAT'),
    ('Turkish Angora', '(not a dog)', 'CAT'),
    ('Indian Hound', 'Indian Pariah (Indie)', 'DOG'),
    ('Bhutia', 'Himalayan Sheepdog (Gaddi)', 'DOG'),
    ('English Mastiff', 'Bullmastiff', 'DOG'),
    ('Minature Pilsner', 'Miniature Pinscher', 'DOG'),
    ('Culture Pom', 'Pomeranian', 'DOG'),
    ('Australian Shepherd', 'Australian Shepherd', 'DOG'),
    ('Terrier mix', '(mixed breed)', 'MIXED'),
    ('shih tzu-Lhasa apso mix', '(mixed breed)', 'MIXED'),
    ('Indie pom cross', '(mixed breed)', 'MIXED'),
    ('British Bulldog', 'English Bulldog', 'DOG'),
    ('lahasa apso', 'Lhasa Apso', 'DOG'),
    ('Shiba Inu', 'Shiba Inu', 'DOG'),
    ('Lhasa & terrier mix', '(mixed breed)', 'MIXED'),
    ('King charles spaniel X shih tzu', '(mixed breed)', 'MIXED'),
    ('maltepoo', '(mixed breed)', 'MIXED'),
    ('Irish Setter', 'Pointer / Setter', 'DOG'),
    ('American Bobtail Cat', '(not a dog)', 'CAT'),
    ('Indie Dacshaun', 'Indian Pariah (Indie)', 'DOG'),
    ('Shih Apso', 'Shih Tzu', 'DOG'),
    ('Presian cat', '(not a dog)', 'CAT'),
    ('Grey Hound', 'Greyhound / Sighthound', 'DOG'),
    ('Cocker Spanial', 'Cocker Spaniel', 'DOG'),
    ('Black German Shepherd', 'German Shepherd', 'DOG'),
    ('WhiteRetriver', 'Golden Retriever', 'DOG'),
    ('Tibetan Spaniel', 'Tibetan Spaniel', 'DOG'),
    ('Gaddi', 'Himalayan Sheepdog (Gaddi)', 'DOG'),
    ('kombai', 'Kombai', 'DOG'),
    ('Afghan Hound', 'Greyhound / Sighthound', 'DOG'),
    ('russian persian mix cat', '(not a dog)', 'CAT'),
    ('Belgian Malinois', 'Belgian Malinois', 'DOG'),
    ('Arabian Mau', '(not a dog)', 'CAT'),
    ('Indie Mix Breed', '(mixed breed)', 'MIXED'),
    ('English Cream Retriever', 'Golden Retriever', 'DOG'),
    ('Toypoodle', 'Toy Poodle', 'DOG'),
    ('Bishon', 'Bichon Frise', 'DOG'),
    ('U.S Miniature', '(unmapped)', 'UNMAPPED'),
    ('labradoodle', '(mixed breed)', 'MIXED'),
    ('GoldenDoodles', '(mixed breed)', 'MIXED'),
    ('Chuvava', 'Chihuahua', 'DOG'),
    ('Beagle and shih tzu mix', '(mixed breed)', 'MIXED'),
    ('Cocker pooh', '(mixed breed)', 'MIXED'),
    ('golden lab mix', '(mixed breed)', 'MIXED'),
    ('Italian Mastiff', 'Bullmastiff', 'DOG'),
    ('Toy Poddle', 'Toy Poodle', 'DOG'),
    ('Husky+German Mix', '(mixed breed)', 'MIXED'),
    ('Indie pom mix', '(mixed breed)', 'MIXED'),
    ('Toy Pomeranian mix', '(mixed breed)', 'MIXED'),
    ('Pom', 'Pomeranian', 'DOG'),
    ('Shih -Tzu', 'Shih Tzu', 'DOG'),
    ('Himalayan shepherd', 'Himalayan Sheepdog (Gaddi)', 'DOG'),
    ('Miniature Pinscher', 'Miniature Pinscher', 'DOG'),
    ('American Shepherd', 'Australian Shepherd', 'DOG'),
    ('Pom Mix', '(mixed breed)', 'MIXED'),
    ('Weimaraner', 'Weimaraner', 'DOG'),
    ('Beagal', 'Beagle', 'DOG'),
    ('Belgium Shepherd', 'Belgian Malinois', 'DOG'),
    ('Pomsky', '(mixed breed)', 'MIXED'),
    ('Staffordshire Bull Terrier', 'Amstaff / Pit-type', 'DOG'),
    ('American Pointer', 'Pointer / Setter', 'DOG'),
    ('Perisan Cat', '(not a dog)', 'CAT'),
    ('Presacanario', '(not a dog)', 'CAT'),
    ('Cocoapoo', '(mixed breed)', 'MIXED'),
    ('Alsation', 'German Shepherd', 'DOG'),
    ('Rhodesian Ridgeback', 'Rhodesian Ridgeback', 'DOG'),
    ('Toy Terrier', 'Terrier (other)', 'DOG'),
    ('Yokshire Terrier', 'Yorkshire Terrier', 'DOG'),
    ('labrador', 'Labrador Retriever', 'DOG'),
    ('German Shorthaired Pointer', 'Pointer / Setter', 'DOG'),
    ('Bishop', 'Bichon Frise', 'DOG'),
    ('Mini Poodle', 'Toy Poodle', 'DOG'),
    ('Parrot', '(not a dog)', 'OTHER ANIMAL'),
    ('Shih', 'Shih Tzu', 'DOG'),
    (' beagle lab mix ', '(mixed breed)', 'MIXED'),
    ('indie-Pom ', 'Indian Pariah (Indie)', 'DOG'),
    ('Bernese Mountain Dog', '(not a dog)', 'CAT'),
    ('Bengal Cat', '(not a dog)', 'CAT'),
    ('Black Labrator', 'Labrador Retriever', 'DOG'),
    ('Indie mix', '(mixed breed)', 'MIXED'),
    ('Cavapoo', '(mixed breed)', 'MIXED'),
    ('Coton De Tulear', 'Havanese', 'DOG'),
    ('French bull dog', 'French Bulldog', 'DOG'),
    ('Sheep Dog', '(unmapped)', 'UNMAPPED'),
    ('Shih Tzu Maltese', 'Shih Tzu', 'DOG'),
    ('Pekingese', 'Pekingese', 'DOG'),
    ('Shih - Tzu', 'Shih Tzu', 'DOG'),
    ('Lab Mix', '(mixed breed)', 'MIXED'),
    ('English Springer Spaniel', 'Springer Spaniel', 'DOG'),
    ('Japanese Dog', '(unmapped)', 'UNMAPPED'),
    ('shih Tzu daschund mix', '(mixed breed)', 'MIXED'),
    ('Mini Doodle', '(mixed breed)', 'MIXED'),
    ('Hound', '(unmapped)', 'UNMAPPED'),
    ('King Charles Spaniel', 'Cavalier King Charles Spaniel', 'DOG'),
    ('daschund', 'Dachshund', 'DOG'),
    ('German shephard', 'German Shepherd', 'DOG'),
    ('Lasha apso', 'Lhasa Apso', 'DOG'),
    ('Love Bird', '(not a dog)', 'OTHER ANIMAL'),
    ('Chaos Spaniel', 'Cocker Spaniel', 'DOG'),
    ('Huskty', 'Siberian Husky', 'DOG'),
    ('Miniature Dachshund', 'Dachshund', 'DOG'),
    ('POODLE', 'Standard Poodle', 'DOG'),
    ('tIBETIAN TERRIER', 'Tibetan Terrier', 'DOG'),
    ('cocker spaniel+poodle', '(mixed breed)', 'MIXED'),
    ('pikinis', 'Pug', 'DOG'),
    ('Mongrel', 'Indian Pariah (Indie)', 'DOG'),
    ('Guinea Pig', '(not a dog)', 'OTHER ANIMAL'),
    ('bully kutta', 'Bully Kutta (Indian Mastiff)', 'DOG'),
    ('Golden retriever mix', '(mixed breed)', 'MIXED'),
    ('lash apso', 'Lhasa Apso', 'DOG'),
    ('Indie-Pom', 'Indian Pariah (Indie)', 'DOG'),
    ('Terrier', 'Terrier (other)', 'DOG'),
    ('mix  poodles', '(mixed breed)', 'MIXED'),
    ('german sheperd/rotweilwe', '(mixed breed)', 'MIXED'),
    ('beagle/husky', '(mixed breed)', 'MIXED'),
    ('Toy Maltese', 'Maltese', 'DOG'),
    ('Miniature pinscher', 'Miniature Pinscher', 'DOG'),
    ('german and Indie Mix', '(mixed breed)', 'MIXED'),
    ('mini maltese', 'Maltese', 'DOG'),
    ('American Shorthair', '(not a dog)', 'CAT'),
    ('Havanese', 'Havanese', 'DOG'),
    ('Hamster', '(not a dog)', 'OTHER ANIMAL'),
    ('German Shepherd Lab Mix', '(mixed breed)', 'MIXED'),
    ('Goden Retriver+Cocker Spaniel', '(mixed breed)', 'MIXED'),
    ('American Staffordshire Terrier', 'Amstaff / Pit-type', 'DOG'),
    ('Muthoot Hound', 'Indian Pariah (Indie)', 'DOG'),
    ('ret', '(unusable)', 'JUNK'),
    ('Bichon Frise', 'Bichon Frise', 'DOG'),
    ('goloden retriver', 'Golden Retriever', 'DOG'),
    ('combi', '(unusable)', 'JUNK'),
    ('Pooshon', '(mixed breed)', 'MIXED'),
    ('Puggle', '(mixed breed)', 'MIXED'),
    ('Belgium Sheep', '(not a dog)', 'OTHER ANIMAL'),
    ('Cavoodle', '(mixed breed)', 'MIXED'),
    ('Ragdoll', '(not a dog)', 'CAT'),
    ('Husky lab  mix', '(mixed breed)', 'MIXED'),
    ('Mastiff', 'Bullmastiff', 'DOG'),
    ('white retriever', 'Golden Retriever', 'DOG'),
    ('toy fOX terrier', 'Terrier (other)', 'DOG'),
    ('cooker spaniel', 'Cocker Spaniel', 'DOG'),
    ('American Akita ', 'Akita', 'DOG'),
    ('Morki', '(mixed breed)', 'MIXED'),
    ('British long hair ', '(not a dog)', 'CAT'),
    ('Poodle', 'Standard Poodle', 'DOG'),
    ('caravan hound', 'Mudhol / Caravan Hound', 'DOG'),
    ('Persian  mix', '(not a dog)', 'CAT'),
    ('Tibetan Terrier', 'Tibetan Terrier', 'DOG'),
    ('Fox Terrier', 'Terrier (other)', 'DOG'),
    ('Chauchau', 'Chow Chow', 'DOG'),
    ('Mudhol Hound', 'Mudhol / Caravan Hound', 'DOG'),
    ('Jack Mals', 'Jack Russell Terrier', 'DOG'),
    ('American Bulldog-Doberman Mix', '(mixed breed)', 'MIXED'),
    ('SHITZU', 'Shih Tzu', 'DOG'),
    ('Rottweiler  Indie mix', '(mixed breed)', 'MIXED'),
    ('Alsatian', 'German Shepherd', 'DOG'),
    ('Jack Russel Te', 'Jack Russell Terrier', 'DOG'),
    ('Shih-tzu', 'Shih Tzu', 'DOG'),
    ('Exotic Shorthair', '(not a dog)', 'CAT'),
    ('Cokerpoo', '(mixed breed)', 'MIXED'),
    ('Persiancat', '(not a dog)', 'CAT'),
    ('Khao Manee', '(not a dog)', 'CAT'),
    ('Beagle , Golden Retriever', '(mixed breed)', 'MIXED'),
    ('German Shepherd mix', '(mixed breed)', 'MIXED'),
    ('mix of maltese and poodle', '(mixed breed)', 'MIXED'),
    ('British Spaniel', '(unmapped)', 'UNMAPPED'),
    ('American Ragdoll Cat', '(not a dog)', 'CAT'),
    ('Australian Cattle Dog', 'Australian Cattle Dog', 'DOG'),
    ('Miniature Poodle', 'Toy Poodle', 'DOG'),
    ('Indie Beagle Mix', '(mixed breed)', 'MIXED'),
    ('Lhasa APSO', 'Lhasa Apso', 'DOG'),
    ('Golden RETRIVER', 'Golden Retriever', 'DOG'),
    ('Miniature Spitz', 'Indian Spitz', 'DOG'),
    ('german shephert', 'German Shepherd', 'DOG'),
    ('French Bulldog + Shih-tzu', '(mixed breed)', 'MIXED'),
    ('Whippet', 'Greyhound / Sighthound', 'DOG'),
    ('maltese mixed', '(mixed breed)', 'MIXED'),
    ('Nepolian mastif', 'Bullmastiff', 'DOG'),
    ('rotweiler', 'Rottweiler', 'DOG'),
    ('Cocor spenial', 'Cocker Spaniel', 'DOG'),
    ('Indian gaddi', 'Himalayan Sheepdog (Gaddi)', 'DOG'),
    ('new found land', 'Saint Bernard', 'DOG'),
    ('multipoo', '(mixed breed)', 'MIXED'),
    ('Pandikona', 'Pandikona', 'DOG'),
    ('-Dalmation', 'Dalmatian', 'DOG'),
    ('American Short hair', '(not a dog)', 'CAT'),
    ('Black German Sepherd', 'German Shepherd', 'DOG'),
    ('Thai cat', '(not a dog)', 'CAT'),
    ('Havenese', 'Havanese', 'DOG'),
    ('29.11.2021', '(unusable)', 'JUNK'),
    ('American ', '(unusable)', 'JUNK'),
    ('Cairn Terrier', 'Terrier (other)', 'DOG'),
    ('cockatiel', '(not a dog)', 'OTHER ANIMAL'),
    ('Indie and spitz mix Dog', '(mixed breed)', 'MIXED'),
    ('schnauzer', 'Miniature Schnauzer', 'DOG'),
    ('Pariah', 'Indian Pariah (Indie)', 'DOG'),
    ('Newfoundland', 'Saint Bernard', 'DOG'),
    ('indie pom mi', 'Indian Pariah (Indie)', 'DOG'),
    ('La', '(unusable)', 'JUNK'),
    ('Yorkie', 'Yorkshire Terrier', 'DOG'),
    ('Maltee Poo', '(mixed breed)', 'MIXED'),
    ('Russian Blue', '(not a dog)', 'CAT'),
    ('Mix Poodles', '(mixed breed)', 'MIXED'),
    ('Shihtzu & Poodle Mix', '(mixed breed)', 'MIXED'),
    ('cane', 'Cane Corso', 'DOG'),
    ('cockerspaniel', 'Cocker Spaniel', 'DOG'),
    ('Indies Cat', '(not a dog)', 'CAT'),
    ('Chiuaua', 'Chihuahua', 'DOG'),
    ('Abyssinian', '(not a dog)', 'CAT'),
    ('indie doberman mix', '(mixed breed)', 'MIXED'),
    ('yorkipoo', '(mixed breed)', 'MIXED'),
    ('Scottish Fold', '(not a dog)', 'CAT'),
    ('German shepherds', 'German Shepherd', 'DOG'),
    ('Cocker Pooh', '(mixed breed)', 'MIXED'),
    ('Labrador+Indie Mix', '(mixed breed)', 'MIXED'),
    ('mix springer spaniel and terrier', '(mixed breed)', 'MIXED'),
    ('Chow chw', 'Chow Chow', 'DOG'),
    ('malti poo', '(mixed breed)', 'MIXED'),
    ('Dobber man', 'Doberman', 'DOG'),
    ('New Foundland', 'Saint Bernard', 'DOG'),
    ('Belgian Shepherd', 'Belgian Malinois', 'DOG'),
    ('belgian mastiff', 'Bullmastiff', 'DOG'),
    ('bug', '(mixed breed)', 'MIXED'),
    ('Papillon', 'Papillon', 'DOG'),
    ('german miniatur', '(unmapped)', 'UNMAPPED'),
    ('Havapoo', '(mixed breed)', 'MIXED'),
    ('Racdoll', '(not a dog)', 'CAT'),
    ('Collie', 'Border Collie', 'DOG'),
    ('Cocker spaniel+indie cross', '(mixed breed)', 'MIXED'),
    ('pignese', 'Pug', 'DOG'),
    ('Airedale Terrier', 'Terrier (other)', 'DOG'),
    ('SHih ztu', 'Shih Tzu', 'DOG'),
    ('Lab-German', 'Labrador Retriever', 'DOG'),
    ('indi beagle mix', '(mixed breed)', 'MIXED'),
    ('Boxer Indie Mix', '(mixed breed)', 'MIXED'),
    ('dober', 'Doberman', 'DOG'),
    ('Teacup Yorkie', 'Yorkshire Terrier', 'DOG'),
    ('Dalmatian-Labrador mix', '(mixed breed)', 'MIXED'),
    ('Cavalier King Charles Spaniel + Poodle', '(mixed breed)', 'MIXED'),
    ('Maltese Pooh', '(mixed breed)', 'MIXED'),
    ('Indie mix Long coat', '(mixed breed)', 'MIXED'),
    ('Chuorkie', '(mixed breed)', 'MIXED'),
    ('Norwegian Forest Cat', '(not a dog)', 'CAT'),
    ('Maltisse', 'Maltese', 'DOG'),
    ('GermanSepherdMixRottweiler', 'Rottweiler', 'DOG'),
    ('GSD*PUG MIX', '(mixed breed)', 'MIXED'),
    ('Lab - German ', 'Labrador Retriever', 'DOG'),
    ('Labrador Spitz Mix', '(mixed breed)', 'MIXED'),
    ('Labrador and Golden Retriever Mixed', '(mixed breed)', 'MIXED'),
    ('Mini Poddle', 'Toy Poodle', 'DOG'),
    ('Doberman- mix', '(mixed breed)', 'MIXED'),
    ('Mix Indiee', '(mixed breed)', 'MIXED'),
    ('Brabamcom', '(unmapped)', 'UNMAPPED'),
    ('West Highland White Terrier', 'Terrier (other)', 'DOG'),
    ('Westie Terrier', 'Terrier (other)', 'DOG'),
    ('american bulldog - doberman mix', '(mixed breed)', 'MIXED'),
    ('great pyranese ', 'Great Pyrenees', 'DOG'),
    ('American eskimo', 'Indian Spitz', 'DOG'),
    ('mini goldon doodle', '(mixed breed)', 'MIXED'),
    ('Chowchow', 'Chow Chow', 'DOG'),
    ('Chow Chow mix', '(mixed breed)', 'MIXED'),
    ('belgian sepherd', 'Belgian Malinois', 'DOG'),
    ('indian terrier', 'Terrier (other)', 'DOG'),
    ('french', 'French Bulldog', 'DOG'),
    ('Lab  Mix Breed', '(mixed breed)', 'MIXED'),
    ('GSD Pug Mix', '(mixed breed)', 'MIXED'),
    ('Rottweiler (nt cooperte wth othr pets)', 'Rottweiler', 'DOG'),
    ('King sheperd', 'German Shepherd', 'DOG'),
    ('minpin', 'Miniature Pinscher', 'DOG'),
    ('German Shepherd + Rottweiler', '(mixed breed)', 'MIXED'),
    ('Long Haired Dachshund', 'Dachshund', 'DOG'),
    ('Black Retriever', 'Golden Retriever', 'DOG'),
    ('Minatare Pincher + Toy Pom', '(mixed breed)', 'MIXED'),
    ('American Curl', '(not a dog)', 'CAT'),
    ('Shi-Tzu', 'Shih Tzu', 'DOG'),
    ('labra spitz mix', '(mixed breed)', 'MIXED'),
    ('Korean spitz', 'Indian Spitz', 'DOG'),
    ('Eskimo', 'Indian Spitz', 'DOG'),
    ('indie Husky', 'Indian Pariah (Indie)', 'DOG'),
    ('Dogo argentino', 'Dogo Argentino', 'DOG'),
    ('BOX', '(unusable)', 'JUNK'),
    ('Syberian cat', '(not a dog)', 'CAT'),
    ('St. Bernard', 'Saint Bernard', 'DOG'),
    ('scottish cat', '(not a dog)', 'CAT'),
    ('sant bernat', 'Saint Bernard', 'DOG'),
    ('rampur hound ', 'Rampur Greyhound', 'DOG'),
    ('puli', 'Other pedigree', 'DOG'),
    ('Indie Spitz', 'Indian Pariah (Indie)', 'DOG'),
    (' Black Retriever', 'Golden Retriever', 'DOG'),
    ('Indie mix cat', '(not a dog)', 'CAT'),
    ('labrador doodle', '(mixed breed)', 'MIXED'),
    ('Chiwawa', 'Chihuahua', 'DOG'),
    ('indian paraya', 'Indian Pariah (Indie)', 'DOG'),
    ('Jack Russell Terrier mix', '(mixed breed)', 'MIXED'),
    ('Ruff kolly', 'Border Collie', 'DOG'),
    ('GSD Husky Mix', '(mixed breed)', 'MIXED'),
    ('PER', '(unusable)', 'JUNK'),
    ('Beagle Lab Mix', '(mixed breed)', 'MIXED'),
    ('Begaul Cat', '(not a dog)', 'CAT'),
    ('Belgian Shephard', 'Belgian Malinois', 'DOG'),
    ('PUG and beagle mix', '(mixed breed)', 'MIXED'),
    ('Pek-shu', '(mixed breed)', 'MIXED'),
    ('Rottweiler Indie mix', '(mixed breed)', 'MIXED'),
    ('vizsla', 'Pointer / Setter', 'DOG'),
    ('persian+Tabby Mix', '(not a dog)', 'CAT'),
    ('Russian Persian Mix Cat', '(not a dog)', 'CAT'),
    ('German-Lab mix', '(mixed breed)', 'MIXED'),
    ('Shihtzu+Lhasa', '(mixed breed)', 'MIXED'),
    ('Barni doodle', '(mixed breed)', 'MIXED'),
    ('Exotic short hair (cat)', '(not a dog)', 'CAT'),
    ('Burmese', '(not a dog)', 'CAT'),
    ('calico cat', '(not a dog)', 'CAT'),
    ('shorkie', '(mixed breed)', 'MIXED'),
    ('Lab+Rot Mix', '(mixed breed)', 'MIXED'),
    ('golden corgi mix', '(mixed breed)', 'MIXED'),
    ('indian spitz Pomeranian mix', '(mixed breed)', 'MIXED'),
    ('Ocicat', '(not a dog)', 'CAT'),
    ('ka', '(unusable)', 'JUNK'),
    ('Pariha', 'Indian Pariah (Indie)', 'DOG'),
    ('mix', '(unusable)', 'JUNK'),
    ('Oriental Shorthair', '(not a dog)', 'CAT'),
    ('Mix', '(unusable)', 'JUNK'),
    ('Dachshund and lab mix', '(mixed breed)', 'MIXED'),
    ('Norfolk Terrier', 'Terrier (other)', 'DOG'),
    ('Dalmatian-Labrador)', 'Labrador Retriever', 'DOG'),
    ('Rott', '(unusable)', 'JUNK'),
    ('Doberman pincher European', 'Doberman', 'DOG'),
    ('Scottish terrier', 'Terrier (other)', 'DOG'),
    ('Egyptian Mau', '(not a dog)', 'CAT'),
    ('English Foxhound', '(unmapped)', 'UNMAPPED'),
    ('Shih Tzu+Lhasa apso mix', '(mixed breed)', 'MIXED'),
    ('English R', '(unmapped)', 'UNMAPPED'),
    ('French Mastiff, Beagle ', '(mixed breed)', 'MIXED'),
    ('Beagle Husky', 'Beagle', 'DOG'),
    ('Lab-Pom mix', '(mixed breed)', 'MIXED'),
    ('bedlington terrier', 'Terrier (other)', 'DOG'),
    ('cain corso', 'Cane Corso', 'DOG'),
    ('chou', '(unmapped)', 'UNMAPPED'),
    ('cocker mix', '(mixed breed)', 'MIXED'),
    ('cocker pug', 'Cocker Spaniel', 'DOG'),
    ('Balinese', '(not a dog)', 'CAT'),
    ('indie long coat', 'Indian Pariah (Indie)', 'DOG'),
    ('Irish labrador', 'Labrador Retriever', 'DOG'),
    ('Irish Terrier', 'Terrier (other)', 'DOG'),
    ('lhasa mix breed', '(mixed breed)', 'MIXED'),
    ('mix of chihuahua and yorkshire terrier', '(mixed breed)', 'MIXED'),
    ('German and Indie Mix', '(mixed breed)', 'MIXED'),
    ('Indie - Retriever Mix', '(mixed breed)', 'MIXED'),
    ('shandong cat ', '(not a dog)', 'CAT'),
    ('Golden mix', '(mixed breed)', 'MIXED'),
    ('Golden Retrievereng', 'Golden Retriever', 'DOG'),
    ('Nebelung', '(not a dog)', 'CAT'),
    ('Indie Dachshund', 'Indian Pariah (Indie)', 'DOG'),
    ('Thai Dog', '(unmapped)', 'UNMAPPED'),
    ('Lovebir', '(not a dog)', 'OTHER ANIMAL'),
    ('lhasa+terrier', '(mixed breed)', 'MIXED'),
    ('Persian cat mix', '(not a dog)', 'CAT'),
    ('Keeshond', 'Other pedigree', 'DOG'),
    ('elkhound', 'Other pedigree', 'DOG'),
    ('Richpack', '(unusable)', 'JUNK'),
    ('Labrador [8 year]', 'Labrador Retriever', 'DOG'),
    ('Siberian Husky / German Shepherd', '(mixed breed)', 'MIXED'),
    ('SPITZ - POM MIX', '(mixed breed)', 'MIXED'),
    ('Shih Tzu Dachshund Mix', '(mixed breed)', 'MIXED'),
    ('Beaski', '(mixed breed)', 'MIXED'),
    ('Cardigan Welsh Corgi', 'Pembroke Corgi', 'DOG'),
    ('Yorkshire biewer', 'Yorkshire Terrier', 'DOG'),
    ('lesepso', 'Lhasa Apso', 'DOG'),
    ('tulturepon', '(unmapped)', 'UNMAPPED'),
    ('Cocker Spaiel', 'Cocker Spaniel', 'DOG'),
    ('Cocker Spaniel ( 9 years)', 'Cocker Spaniel', 'DOG'),
    ('Persian & Siberian Mix', '(not a dog)', 'CAT'),
    ('Lhasaa', 'Lhasa Apso', 'DOG'),
    ('Siberian Shepherd', '(unmapped)', 'UNMAPPED'),
    ('Sebrian', '(not a dog)', 'CAT'),
    ('lab+saluki mix', '(mixed breed)', 'MIXED'),
    ('English Pointer', 'Pointer / Setter', 'DOG'),
    ('Mix indie border coolie', '(mixed breed)', 'MIXED'),
    ('Mane cone', '(not a dog)', 'CAT'),
    ('Great Pyrenees', 'Great Pyrenees', 'DOG'),
    ('Portuguese water dog', 'Other pedigree', 'DOG'),
    ('Mixed Breed cat', '(not a dog)', 'CAT'),
    ('samo', 'Samoyed', 'DOG'),
    ('Old English Sheepdog', 'Other pedigree', 'DOG'),
    ('Tatra Shepherd Dog ', 'Other pedigree', 'DOG'),
    ('Bombay', '(not a dog)', 'CAT'),
    ('Short hair Havanese', 'Havanese', 'DOG'),
    ('cavachon', '(mixed breed)', 'MIXED'),
    ('DaschundLab Mixed', '(mixed breed)', 'MIXED'),
    ('pom + golden retriver', '(mixed breed)', 'MIXED'),
    ('Tibetan Apso', 'Lhasa Apso', 'DOG'),
    ('GSD and Indie mix', '(mixed breed)', 'MIXED'),
    ('German & Husky Mix', '(mixed breed)', 'MIXED'),
    ('Semi persian cat', '(not a dog)', 'CAT'),
    ('Beagle and cat', '(not a dog)', 'CAT'),
    ('saiberian', '(not a dog)', 'CAT'),
    ('Indie + Persian Mix', '(not a dog)', 'CAT'),
    ('Himalayan ragdoll', '(not a dog)', 'CAT'),
    ('Mix poodle', '(mixed breed)', 'MIXED'),
    ('American Wirehair', '(not a dog)', 'CAT'),
    ('Sheba Inu', 'Shiba Inu', 'DOG'),
    ('Pekingese Mix Breed', '(mixed breed)', 'MIXED'),
    ('pikaso pablo', 'Pekingese', 'DOG'),
    ('Toddy', '(unusable)', 'JUNK'),
    ('Goolden', '(unmapped)', 'UNMAPPED'),
    ('German Miniature', '(unmapped)', 'UNMAPPED'),
    ('Devon Rex', '(not a dog)', 'CAT'),
    ('Giant Poodle', 'Standard Poodle', 'DOG'),
    ('Lhasa & Terr', '(mixed breed)', 'MIXED'),
    ('Lasa Terrier Mix', '(mixed breed)', 'MIXED'),
    ('Birman', '(not a dog)', 'CAT'),
    ('Beagle and Husky Mix', '(mixed breed)', 'MIXED'),
    ('Borzoi', 'Greyhound / Sighthound', 'DOG'),
    ('White  Terrier', 'Terrier (other)', 'DOG'),
    ('Labra Doodle', '(mixed breed)', 'MIXED'),
    ('TPoodle+Lasha', '(mixed breed)', 'MIXED'),
    ('Border Terrier', 'Terrier (other)', 'DOG'),
    ('Basenji', 'Other pedigree', 'DOG'),
    ('Boston Terrier', 'English Bulldog', 'DOG'),
    ('cocke', 'Cocker Spaniel', 'DOG'),
    ('Golden and Pom mix', '(mixed breed)', 'MIXED'),
    ('Korat', '(not a dog)', 'CAT'),
    ('Kokupu', '(unusable)', 'JUNK'),
    ('dob', '(unusable)', 'JUNK'),
    ('Mix Bully', '(mixed breed)', 'MIXED'),
    ('Golden pome', 'Pomeranian', 'DOG'),
    ('Shipoo', '(mixed breed)', 'MIXED'),
    ('poodeln]', 'Standard Poodle', 'DOG'),
    ('indie Calico', '(not a dog)', 'CAT'),
    ('pitbull terrier', 'Amstaff / Pit-type', 'DOG'),
    ('toy beagle', 'Beagle', 'DOG'),
    ('indie long coat cat', '(not a dog)', 'CAT'),
    ('GSD puppy', 'German Shepherd', 'DOG'),
    ('Anatolian Shepherd', 'Other pedigree', 'DOG'),
    ('kangal', 'Other pedigree', 'DOG'),
    ('Afganistan Haund', 'Greyhound / Sighthound', 'DOG'),
    ('Antolian shepherd', 'Other pedigree', 'DOG'),
    ('peengese', 'Pekingese', 'DOG'),
    ('Dober mann', 'Doberman', 'DOG'),
    ('tibetian Spaniel', 'Tibetan Spaniel', 'DOG'),
    ('Flat-Coated Retriever', '(unmapped)', 'UNMAPPED'),
    ('Malshi', '(mixed breed)', 'MIXED'),
    ('Iindian Hound', 'Indian Pariah (Indie)', 'DOG'),
    ('pyranese pit', 'Great Pyrenees', 'DOG'),
    ('Pikinis', 'Pug', 'DOG'),
    ('Shih Tzu Maltese Mix', '(mixed breed)', 'MIXED'),
    ('Toy Beagle', 'Beagle', 'DOG'),
    ('Javanese', '(not a dog)', 'CAT'),
    ('Japanies Akita', 'Akita', 'DOG'),
    ('persian and indie mix', '(not a dog)', 'CAT'),
    ('Agouti Husky', 'Siberian Husky', 'DOG'),
    ('American', '(unusable)', 'JUNK'),
    ('American hairwire', '(unmapped)', 'UNMAPPED'),
    ('persian cat grooming', '(not a dog)', 'CAT'),
    ('Tonkinese', '(not a dog)', 'CAT'),
    ('poodle grooming', '(unmapped)', 'UNMAPPED'),
    ('Simba', '(unusable)', 'JUNK'),
    ('Chesapeake Bay Retriever', '(unmapped)', 'UNMAPPED'),
    ('mini pinshecir', 'Miniature Pinscher', 'DOG'),
    ('Cornish Rex', '(not a dog)', 'CAT'),
    ('pocket bully', 'Amstaff / Pit-type', 'DOG'),
    ('Persian himalayan', '(not a dog)', 'CAT'),
    ('INDI GERMAN SHEPERD', 'German Shepherd', 'DOG'),
    ('shor', '(unusable)', 'JUNK'),
    ('Lab Doodle', '(mixed breed)', 'MIXED'),
    ('Lab Poodle Mix', '(mixed breed)', 'MIXED'),
    ('shiz', '(unusable)', 'JUNK'),
    ('Munchkin', '(not a dog)', 'CAT'),
    ('..', '(unusable)', 'JUNK'),
    ('Amrican husky', 'Siberian Husky', 'DOG'),
    ('australian silky terrier', 'Terrier (other)', 'DOG'),
    ('ZOEY', '(unusable)', 'JUNK'),
    ('Maltese mixed', '(mixed breed)', 'MIXED'),
    ('Manx', '(not a dog)', 'CAT'),
    ('Bull Terrier', 'Terrier (other)', 'DOG'),
    ('AUSTRALIAN KELPIE', 'Australian Cattle Dog', 'DOG'),
    ('Vizsla', 'Pointer / Setter', 'DOG'),
    ('Mix Persian', '(not a dog)', 'CAT'),
    ('Singapura', '(not a dog)', 'CAT'),
    ('Somali', '(not a dog)', 'CAT'),
    ('Sphynx', '(not a dog)', 'CAT'),
    ('Burmilla', '(not a dog)', 'CAT'),
    ('Tatra Shepherd Dog', 'Other pedigree', 'DOG'),
    ('Thai Cat', '(not a dog)', 'CAT'),
    ('Toyger', '(not a dog)', 'CAT'),
    ('turkey sango', '(unmapped)', 'UNMAPPED'),
    ('turtle', '(not a dog)', 'OTHER ANIMAL'),
    ('Yorkipoo', '(mixed breed)', 'MIXED'),
    ('Yorkshire teacup', 'Yorkshire Terrier', 'DOG'),
    ('Zara', '(unusable)', 'JUNK'),
    ('Gordon setter', 'Pointer / Setter', 'DOG'),
    ('Sant bernat', 'Saint Bernard', 'DOG'),
    ('GR & Lab mix', '(mixed breed)', 'MIXED'),
    ('Sant Bernat', 'Saint Bernard', 'DOG'),
    ('GR Mixed Pome', '(mixed breed)', 'MIXED'),
    ('couton', '(mixed breed)', 'MIXED'),
    ('Australian mountain doodle', '(mixed breed)', 'MIXED'),
    ('grey ghost', 'Weimaraner', 'DOG'),
    ('griff', '(unmapped)', 'UNMAPPED'),
    ('GSD mixed', '(mixed breed)', 'MIXED'),
    ('Italian Greyhound', 'Greyhound / Sighthound', 'DOG'),
    ('Indo pers', '(unmapped)', 'UNMAPPED'),
    ('German Cat', '(not a dog)', 'CAT'),
    ('Mixed Breed ( lab & Boxer)', '(mixed breed)', 'MIXED'),
    ('German Shepherd [12.5year]', 'German Shepherd', 'DOG'),
    ('moltis', 'Maltese', 'DOG'),
    ('Dalmatian-Labrador', 'Labrador Retriever', 'DOG'),
    ('Indie & pomea', '(mixed breed)', 'MIXED'),
    ('Indie & Husky Mix', '(mixed breed)', 'MIXED'),
    ('poin', '(unusable)', 'JUNK'),
    ('pre', '(unusable)', 'JUNK'),
    ('Briard', 'Other pedigree', 'DOG'),
    ('Liver Shepherd', 'German Shepherd', 'DOG'),
    ('london terrier', 'Terrier (other)', 'DOG'),
    ('Indo pers & Sai', '(mixed breed)', 'MIXED'),
    ('New Zealand white rabbit', '(not a dog)', 'OTHER ANIMAL'),
    ('Shetland', 'Other pedigree', 'DOG'),
    ('Panda chow chow', 'Chow Chow', 'DOG'),
    ('Snowshoe', '(not a dog)', 'CAT'),
    ('Chi', 'Chihuahua', 'DOG'),
    ('Mix Persian with Indie', '(not a dog)', 'CAT'),
    ('Sugar Glider', '(not a dog)', 'OTHER ANIMAL'),
    ('Pyrenees Pit', 'Great Pyrenees', 'DOG'),
    ('Arabian Malinois', 'Belgian Malinois', 'DOG'),
    ('Neapolitan Mastiff', 'Bullmastiff', 'DOG'),
    ('highland terrier', 'Terrier (other)', 'DOG'),
    ('Bostain Terrier', 'English Bulldog', 'DOG'),
    ('Asian cat', '(not a dog)', 'CAT'),
    ('Kimi', '(unusable)', 'JUNK'),
    ('Mix (Maltese & Pomerian)', '(mixed breed)', 'MIXED'),
    ('rabbits', '(not a dog)', 'OTHER ANIMAL'),
    ('Peterbald', '(not a dog)', 'CAT'),
    ('Indian Mongrels', 'Indian Pariah (Indie)', 'DOG'),
    ('Chartreux', '(not a dog)', 'CAT'),
    ('cpc', '(unusable)', 'JUNK'),
    ('couton de tulaer', '(mixed breed)', 'MIXED'),
    ('LaPerm', '(not a dog)', 'CAT'),
    ('chuw', '(unusable)', 'JUNK'),
    ('sari', '(unusable)', 'JUNK'),
    ('Cavachon', '(mixed breed)', 'MIXED'),
    ('Lab & Beagle', '(mixed breed)', 'MIXED'),
    ('bea', '(unusable)', 'JUNK'),
    ('Bug', '(mixed breed)', 'MIXED'),
    ('Yorkshire Terrier Dog breed', 'Yorkshire Terrier', 'DOG'),
    ('Selkirk Rex', '(not a dog)', 'CAT'),
    ('Shandong Cat', '(not a dog)', 'CAT'),
    ('Biewer', 'Yorkshire Terrier', 'DOG'),
    ('British long hair', '(not a dog)', 'CAT'),
    ('Shih Tzu with Ashang', 'Shih Tzu', 'DOG'),
    ('Shih Tzu(Kaushik)', 'Shih Tzu', 'DOG'),
    ('shetland sheepdog', 'Other pedigree', 'DOG'),
    ('Tofu', '(unusable)', 'JUNK'),
    ('Shar Pei', 'Shar Pei', 'DOG'),
    ('Boerboel', 'Other pedigree', 'DOG'),
    ('mix of labrador and German shepherd', '(mixed breed)', 'MIXED'),
    ('English grooming', '(unmapped)', 'UNMAPPED'),
    ('Alibi', '(unusable)', 'JUNK'),
    ('Lhasa Apso & Maltese mix', '(mixed breed)', 'MIXED'),
    ('maltier', 'Maltese', 'DOG'),
    ('ozzy shepherd Mix', '(mixed breed)', 'MIXED'),
    ('Chlocholate Labrador', 'Labrador Retriever', 'DOG'),
    ('Akopo', '(unusable)', 'JUNK')
)
-- ---------------------------------------------------------------------
-- Example: how many pets per clean breed, dogs only.
-- Replace everything below this line with your real query.
SELECT bc.canonical AS breed, count(*) AS pets
FROM res_partner_pet p
LEFT JOIN pet_breed b ON b.id = p.breed
LEFT JOIN breed_clean bc
       ON bc.raw_breed = coalesce(to_jsonb(b.name)->>'en_US', b.name::text)
WHERE bc.kind = 'DOG'
GROUP BY 1
ORDER BY 2 DESC;
